### ISSUE TITLE
Speech recognition and speech production - KP

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/naur#31]
[Filed on behalf of Kim Patch]

Regarding REQ 13b: If the system's confidence in its recognition of the user's utterance is below a reasonable threshold, prompt the user to repeat or confirm the request made or the information spoken.

I'm not so sure this is a good solution. It sounds logical, but for a project I was involved with about three years ago I looked at speech recognition confidence levels of state-of-the-art speech input and was surprised to see that confidence levels didn't correlate well with what the system got right. We were thinking we could use them to mark what was more likely incorrect to speed proofing and correction, but it was not useful at all and we ended up abandoning the idea. I'd make sure there's research behind this. There's also a whole history of speech input systems prompting users for things that are frustrating for users to be prompted for, because the software makers don't have enough lived experience.

**Comment by jasonjgw** [comment]
Perhaps we should update the discussion in the text to note that this strategy is only appropriate if the system's confidence estimates are highly correlated with its actual recognition accuracy.

The same point has been made with reference to recognition accuracy in other areas (e.g., image recognition), in which giving the user a confidence assessment can be very misleading if the confidence levels don't correspond to the actual probability of correctness.

**Comment by joshueoconnor** [comment]
Very interesting to note that user confidence doesn't correlate with the systems accuracy.  There could be other things at play, such as trust, the nature of the tasks the user wishes to perform, context of use etc.

**Comment by jasonjgw** [comment]
I've proposed adding a note to clarify these issues. See PR #33.
