### ISSUE TITLE
6.6 Designing for understanding and effective use - KP

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/naur#32]
[Filed on behalf of Kim Patch]

REQ 18a: Design the system to respond appropriately to a variety of alternative words, phrases and sentences that may be used to ask the same question, to give the same command, or to supply the same information.
REQ 18b: Design the system to respond appropriately to words and phrases that are likely to be familiar to users of other systems with similar features.

This is tricky territory. Designing a system to respond to a variety of words has pros and cons.
It's good for novice users who happen to hit the right words. But even still it's easy to leave out phrases people might want to say, and when you tell users they can say anything this gets frustrating. Dragon has 24 ways to say go to the end of the line, and one of them isn't "Go End".

It also takes more cognitive effort to come up with one of a variety of phrases then to learn one way and eventually it becomes habit. The way to mitigate the high cognitive load that speech entails is to be consistent, and enabling a lot of synonyms is not that.
Saying anything you want may be good if you are doing something for the first and only time, but it inhibits learning and slows you down if it's something you do over and over again.

The more commands in a system, the greater the chance something is misheard and the more difficult it is to figure out what is wrong.

Low latency is very important for speech input, and for large systems more commands increases latency.
So I think the bottom line is the advice here depends on the application. The key thing users have asked for from developers around this is the ability to disable, change, save and share commands. Asking developers to do this would solve many problems for both users and developers.

**Comment by jasonjgw** [comment]
I think we may wish to add the suggested strategy of enabling the saving and sharing of commands, but this doesn't address the cognitive demands associated with learning a specific command syntax or vocabulary. Synonyms partly address that concern, as does acceptance of different phrases or sentence structures.

Perhaps a better approach would be: document at least one utterance that is supported for each aspect of the system's functionality (e.g., each feature or each step in a dialogue), but also make the system relatively liberal in what it will accept, so the user doesn't have to provide exactly the documented input. This would support users who are new to the system, as well as those who don't remember one of the documented terms/phrases.

**Comment by joshueoconnor** [comment]
I like these comments as they also relate to interesting areas like what are the natural affordances inherent in these systems?

**Comment by jasonjgw** [comment]
I've drafted a proposal in PR #34.
